<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-08-29T18:13:12 IST" name="All Test Suite" finished-at="2023-08-29T18:13:55 IST" duration-ms="43482">
    <groups>
    </groups>
    <test started-at="2023-08-29T18:13:12 IST" name="D:/work/document-profile-ui-automation" finished-at="2023-08-29T18:13:55 IST" duration-ms="43482">
      <class name="com.practice.tests.RegisterPageTests">
        <test-method is-config="true" signature="initReports()[pri:0, instance:com.practice.tests.RegisterPageTests@313b2ea6]" started-at="2023-08-29T18:13:11 IST" name="initReports" finished-at="2023-08-29T18:13:12 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initReports -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.practice.tests.RegisterPageTests@313b2ea6]" started-at="2023-08-29T18:13:12 IST" name="setUp" finished-at="2023-08-29T18:13:19 IST" duration-ms="6932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateNavigationToRegisterPage()[pri:0, instance:com.practice.tests.RegisterPageTests@313b2ea6]" started-at="2023-08-29T18:13:19 IST" name="validateNavigationToRegisterPage" description="To validate that user can navigate to Register page from home page" finished-at="2023-08-29T18:13:21 IST" duration-ms="1433" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateNavigationToRegisterPage -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.practice.tests.RegisterPageTests@313b2ea6]" started-at="2023-08-29T18:13:21 IST" name="tearDown" finished-at="2023-08-29T18:13:21 IST" duration-ms="442" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="tearDownReports()[pri:0, instance:com.practice.tests.RegisterPageTests@313b2ea6]" started-at="2023-08-29T18:13:55 IST" name="tearDownReports" finished-at="2023-08-29T18:13:56 IST" duration-ms="615" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownReports -->
      </class> <!-- com.practice.tests.RegisterPageTests -->
      <class name="com.practice.tests.LoginPageTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:21 IST" name="setUp" finished-at="2023-08-29T18:13:27 IST" duration-ms="6179" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLogin(java.util.Map)[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:27 IST" name="validateLogin" description="To validate that user can navigate to Login page from home page" data-provider="getData" finished-at="2023-08-29T18:13:29 IST" duration-ms="1520" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{testname=validateLogin, execute=yes, browser=chrome, username=test1091@gmail.com, password=^^^^}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.practice.tests.LoginPageTests.validateLogin(LoginPageTests.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.practice.runner.MainRunner.main(MainRunner.java:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:29 IST" name="tearDown" finished-at="2023-08-29T18:13:30 IST" duration-ms="678" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:30 IST" name="setUp" finished-at="2023-08-29T18:13:36 IST" duration-ms="6167" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLogin(java.util.Map)[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:36 IST" name="validateLogin" description="To validate that user can navigate to Login page from home page" data-provider="getData" finished-at="2023-08-29T18:13:37 IST" duration-ms="1555" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{testname=validateLogin, execute=yes, browser=edge, username=iuegf@gmail.com, password=password}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.practice.tests.LoginPageTests.validateLogin(LoginPageTests.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.practice.runner.MainRunner.main(MainRunner.java:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:37 IST" name="tearDown" finished-at="2023-08-29T18:13:38 IST" duration-ms="741" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:38 IST" name="setUp" finished-at="2023-08-29T18:13:44 IST" duration-ms="6013" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLogin(java.util.Map)[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:44 IST" name="validateLogin" description="To validate that user can navigate to Login page from home page" data-provider="getData" finished-at="2023-08-29T18:13:46 IST" duration-ms="1457" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{testname=validateLogin, execute=yes, browser=chrome, username=dwd6@gmail.com, password=wd7712}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Account] but found [Account Login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Account] but found [Account Login]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.practice.tests.LoginPageTests.validateLogin(LoginPageTests.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.practice.runner.MainRunner.main(MainRunner.java:19)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:46 IST" name="tearDown" finished-at="2023-08-29T18:13:47 IST" duration-ms="608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:47 IST" name="setUp" finished-at="2023-08-29T18:13:52 IST" duration-ms="5908" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="validateLogin(java.util.Map)[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:52 IST" name="validateLogin" description="To validate that user can navigate to Login page from home page" data-provider="getData" finished-at="2023-08-29T18:13:54 IST" duration-ms="1996" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{testname=validateLogin, execute=yes, browser=edge, username=test1091@gmail.com, password=password}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.practice.tests.LoginPageTests@21b2e768]" started-at="2023-08-29T18:13:54 IST" name="tearDown" finished-at="2023-08-29T18:13:55 IST" duration-ms="571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.practice.tests.LoginPageTests -->
    </test> <!-- D:/work/document-profile-ui-automation -->
  </suite> <!-- All Test Suite -->
</testng-results>
